# Generated by Django 3.1.1 on 2020-12-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
