# Generated by Django 3.1.1 on 2020-12-05 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Blog')], default=0)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
