# Generated by Django 3.1.1 on 2020-12-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201204_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('Blog', 'Blog')], default='Blog', max_length=10),
        ),
    ]
