# Generated by Django 3.1.1 on 2020-12-08 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0003_auto_20201204_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='TopPost',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('Blog', 'Blog')], default='Blog', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
