# Generated by Django 3.1.1 on 2020-12-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201208_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='TopPost',
        ),
    ]
