# Generated by Django 3.1.1 on 2020-12-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_blogpost_toppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='TopPost',
            field=models.BooleanField(default=False),
        ),
    ]
