# Generated by Django 3.1.1 on 2020-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogpost_toppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='TopPost',
            field=models.BooleanField(default=False, verbose_name='Top Post'),
        ),
    ]
