# Generated by Django 3.1.1 on 2020-12-09 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0008_auto_20201208_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
