# Generated by Django 3.1.1 on 2020-12-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20201208_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
    ]
