# Generated by Django 3.1.1 on 2020-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_remove_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='yolo'),
            preserve_default=False,
        ),
    ]
