# Generated by Django 3.1.1 on 2020-12-13 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20201211_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateField(default=datetime.date.today, help_text='YYYY-MM-DD', verbose_name='Date Created'),
        ),
    ]
