# Generated by Django 3.1.4 on 2020-12-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_1_rating',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_2_rating',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_3_rating',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_4_rating',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='overall',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
