# Generated by Django 3.1.4 on 2020-12-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_auto_20201224_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='categories', to='Reviews.Category'),
        ),
    ]
