# Generated by Django 3.1.4 on 2020-12-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_auto_20201224_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryone', to='Reviews.category'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorytwo', to='Reviews.category'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorythree', to='Reviews.category'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='category_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryfour', to='Reviews.category'),
        ),
    ]
