# Generated by Django 3.1.1 on 2020-12-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogposts',
        ),
    ]
