# Generated by Django 3.1.1 on 2020-12-12 02:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
                ('created', models.DateField(default=datetime.date.today, verbose_name='Date Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('top_post', models.BooleanField(default=False, verbose_name='Top Post')),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], verbose_name='Draft/Publish')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, editable=False, related_name='vlogpost_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vlog Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_comments', to='Vlog.vlogpost')),
            ],
            options={
                'verbose_name': 'Vlog Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date'],
            },
        ),
    ]
